# Site settings
title: Alex Rudy
email: hello@alexrudy.net
description: >
  This is my home page, and a landing for a few personal projects.
  Professionally, I work on the Machine Learning Platform for Discord.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alexrudy.net" # the base hostname & protocol for your site

github_username: alexrudy
linkedin_username: alexrudy
mastodon:
  - username: alexrudy
    instance: hachyderm.io

# Use the default theme
theme: minima
show_excerpts: true

# Collection Settings
collections: []

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from

exclude:
  - docker-compose*.yml
  - Dockerfile
  - README.md
  - tasks.py
  - scripts

header_pages:
  - about.md
  - cv.md

# Defaults
defaults:
  - scope:
      path: ""
    values:
      nav: yes
