version: '3.4'

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

services:
  nginx-alexrudy:
    image: ghcr.io/alexrudy/alexrudy-net:latest
    networks:
      - reverse-proxy
    restart: unless-stopped
