version: '3.4'

services:
  nginx-alexrudy:
    build:
      context: .
      args:
        - JEKYLL_ENV=development
    image: docker.alexrudy.local/alexrudy-jekyll:latest 
    environment:
      - VIRTUAL_HOST=www.alexrudy.local
      - LETSENCRYPT_HOST=
    volumes:
      - .:/src/jekyll-site
      - ./nginx/:/etc/nginx/conf.d/