services:
  nginx-alexrudy:
    build:
      context: .
      args:
        - JEKYLL_ENV=development
    image: registry.alexrudy.test:8082/alexrudy/alexrudy-net:latest
    environment:
      - VIRTUAL_HOST=www.alexrudy.test,alexrudy.test
