services:
  nginx-alexrudy:
    build:
      context: .
      args:
        - JEKYLL_ENV=development
    image: alexrudy-net:latest
    environment:
      - VIRTUAL_HOST=www.alexrudy.net,alexrudy.net
      - LETSENCRYPT_HOST=
    ports:
      - "8083:80"
