version: '3.4'

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

services:
  nginx-alexrudy-org:
    image: docker.alexrudy.net/alexrudy-jekyll:latest
    ports:
      - "8000:80"
    networks:
      - reverse-proxy
    environment:
      - VIRTUAL_HOST=www.alexrudy.org,alexrudy.org,www.alexrudy.net,alexrudy.net
      - LETSENCRYPT_HOST=www.alexrudy.org,alexrudy.org,www.alexrudy.net,alexrudy.net
    restart: unless-stopped