version: '3.4'

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

services:
  nginx-alexrudy:
    image: docker.alexrudy.net/alexrudy-jekyll:latest
    networks:
      - reverse-proxy
    environment:
      - VIRTUAL_HOST=www.alexrudy.net,alexrudy.net
      - LETSENCRYPT_HOST=www.alexrudy.net,alexrudy.net
    restart: unless-stopped