version: '3.4'

services:
  nginx-alexrudy:
    build:
      context: .
      args:
        - JEKYLL_ENV=development
    image: alexrudy-net:latest
    environment:
      - VIRTUAL_HOST=www.alexrudy.local
      - LETSENCRYPT_HOST=
