services:
  nginx-alexrudy:
    build:
      context: .
      args:
        - JEKYLL_ENV=development
    image: alexrudy-net:latest
    environment:
      - VIRTUAL_HOST=www.alexrudy.test
    volumes:
      - .:/src/jekyll-site
      - ./nginx/:/etc/nginx/conf.d/
