name: Build and Publish Website
on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Setup Just
        uses: extractions/setup-just@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: actions/checkout@v2
      - name: Build Docker Contianers
        run: |
          just publish